In [1]:
import numpy as np

# 1. np.array는 하나의 데이터타입만 가질 수 있다.
### (feat. dtype, shape, array, ones, zeros)

In [3]:
data1 = [6, 7.5, 8, 9]
arr = np.array(data1)

In [4]:
arr

array([6. , 7.5, 8. , 9. ])

In [36]:
arr.dtype

dtype('float64')

In [5]:
arr.shape

(4,)

In [6]:
data2 = [[1, 2, 3, 4],
         [5, 6, 7, 8]]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.shape

(2, 4)

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

# 2. astype을 이용해 데이터 타입을 변경할 수 있다.

In [19]:
arr3 = np.array([1, 2, 3, 4, 5], dtype = np.float64)

In [20]:
arr3.dtype

dtype('float64')

In [21]:
arr2 = arr2.astype(np.int64)

In [22]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int64)

In [23]:
int_arr3 = arr3.astype(np.int64)

In [24]:
int_arr3.dtype

dtype('int64')

# 3. 사칙연산을 비롯한 여러 계산을 할 수도 있다.

In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float64)
arr2 = np.array([[7, 8, 9], [10, 11, 12]], dtype = np.float64)

In [26]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [28]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [29]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [30]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [31]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [33]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [34]:
arr1 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [35]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])