In [1]:
import numpy as np

# 1. Numpy 배열의 꽃은 인덱싱이다.

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

In [10]:
arr2d[2, :]

array([ 9, 10, 11, 12])

In [11]:
arr2d[:3, :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr2d[:, 3]

array([ 4,  8, 12, 16])

In [14]:
arr2d[:, :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [15]:
arr2d[3, 2]

15

In [17]:
arr2d[:2, 1:3] = 0

In [18]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# 2. 불리언 인덱싱

In [24]:
names = np.array(["Charles", "Kilho", "Hayoung", "Charles", "Hayoung", "Kilho", "Kilho"])
data = np.random.randn(7, 4)

In [25]:
names

array(['Charles', 'Kilho', 'Hayoung', 'Charles', 'Hayoung', 'Kilho',
       'Kilho'], dtype='<U7')

In [26]:
data

array([[-0.68772915, -0.71829982, -1.00765906,  0.61090543],
       [ 0.19281371, -0.05484207,  0.86577378, -1.31706824],
       [ 0.13864446, -0.08798734, -0.14001234,  0.41758033],
       [ 0.5876368 , -0.75820187, -0.45515684,  0.46020525],
       [-1.25072221,  0.35837758, -1.01265186, -0.31473743],
       [-1.44480192,  0.34123199, -0.01123799,  0.96685872],
       [-0.44120901, -1.30446119, -0.21557118, -1.31214558]])

In [27]:
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [28]:
data[names == "Charles", :]

array([[-0.68772915, -0.71829982, -1.00765906,  0.61090543],
       [ 0.5876368 , -0.75820187, -0.45515684,  0.46020525]])

In [35]:
data[names == "Kilho", :]

array([[ 0.19281371, -0.05484207,  0.86577378, -1.31706824],
       [-1.44480192,  0.34123199, -0.01123799,  0.96685872],
       [-0.44120901, -1.30446119, -0.21557118, -1.31214558]])

In [36]:
data[(names == "Charles") | (names == "Kilho"), :]

array([[-0.68772915, -0.71829982, -1.00765906,  0.61090543],
       [ 0.19281371, -0.05484207,  0.86577378, -1.31706824],
       [ 0.5876368 , -0.75820187, -0.45515684,  0.46020525],
       [-1.44480192,  0.34123199, -0.01123799,  0.96685872],
       [-0.44120901, -1.30446119, -0.21557118, -1.31214558]])

In [37]:
data[:, 3]

array([ 0.61090543, -1.31706824,  0.41758033,  0.46020525, -0.31473743,
        0.96685872, -1.31214558])

In [39]:
data[:, 3] < 0

array([False,  True, False, False,  True, False,  True])

In [40]:
data[data[:, 3] < 0, :]

array([[ 0.19281371, -0.05484207,  0.86577378, -1.31706824],
       [-1.25072221,  0.35837758, -1.01265186, -0.31473743],
       [-0.44120901, -1.30446119, -0.21557118, -1.31214558]])

In [41]:
data[data[:, 3] < 0, :] = 0

In [42]:
data

array([[-0.68772915, -0.71829982, -1.00765906,  0.61090543],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.13864446, -0.08798734, -0.14001234,  0.41758033],
       [ 0.5876368 , -0.75820187, -0.45515684,  0.46020525],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.44480192,  0.34123199, -0.01123799,  0.96685872],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])