In [1]:
import numpy as np

# 1. sqrt, log10, maximum, sum, mean....

In [2]:
arr = np.arange(1, 10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [8]:
x = np.random.randn(8)
y = np.random.randn(8)

In [9]:
x

array([-0.02364152,  1.44557318, -0.28290219,  0.55518026,  0.25102656,
        0.33811295, -0.58010021, -1.16421328])

In [10]:
y

array([-0.01462996,  0.43070333, -0.51440704, -1.16865174,  0.40720146,
       -0.79099761,  1.51871752,  2.30405338])

In [11]:
np.maximum(x, y)

array([-0.01462996,  1.44557318, -0.28290219,  0.55518026,  0.40720146,
        0.33811295,  1.51871752,  2.30405338])

In [12]:
arr = np.random.randn(5, 4)

In [13]:
arr

array([[-0.16851438, -0.83430668,  1.81437139, -0.67257652],
       [-0.77563263,  0.88611515, -1.04965566, -0.50607367],
       [-1.00166833, -0.38521463, -0.03609842, -1.70332824],
       [ 0.50878522, -1.94137534,  1.5555812 , -0.26617974],
       [ 0.94825752, -0.12507344, -1.6935314 , -0.38529623]])

In [14]:
arr.sum()

-5.831414853107428

In [15]:
arr.mean()

-0.2915707426553714

In [16]:
arr.std()

1.0004342482967024

In [17]:
arr.sum(axis=0)

array([-0.48877261, -2.39985494,  0.5906671 , -3.53345441])

In [18]:
arr.sum(axis=1)

array([ 0.1389738 , -1.44524681, -3.12630964, -0.14318866, -1.25564355])

In [19]:
arr > 0

array([[False, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False],
       [ True, False,  True, False],
       [ True, False, False, False]])

In [23]:
(arr > 0).sum()

5

# 2. sort, unique

In [25]:
arr = np.random.randn(8)

In [26]:
arr

array([-0.8542939 , -1.18263336, -1.07201335, -0.83240392,  0.11142223,
        1.25021132,  0.9167663 ,  0.19911086])

In [27]:
np.sort(arr)

array([-1.18263336, -1.07201335, -0.8542939 , -0.83240392,  0.11142223,
        0.19911086,  0.9167663 ,  1.25021132])

In [28]:
np.sort(arr)[::-1]

array([ 1.25021132,  0.9167663 ,  0.19911086,  0.11142223, -0.83240392,
       -0.8542939 , -1.07201335, -1.18263336])

In [29]:
arr = np.random.randn(5, 3)

In [30]:
arr

array([[-0.56107036, -1.10155836,  0.92338016],
       [-1.95950902,  0.98788256, -0.51974942],
       [ 0.45026765, -0.00285286,  1.7950933 ],
       [ 1.07947693, -0.21026694,  0.60826436],
       [ 1.02261858, -1.31269416,  1.21754931]])

In [31]:
np.sort(arr, axis=0)

array([[-1.95950902, -1.31269416, -0.51974942],
       [-0.56107036, -1.10155836,  0.60826436],
       [ 0.45026765, -0.21026694,  0.92338016],
       [ 1.02261858, -0.00285286,  1.21754931],
       [ 1.07947693,  0.98788256,  1.7950933 ]])

In [32]:
np.sort(arr, axis=1)

array([[-1.10155836, -0.56107036,  0.92338016],
       [-1.95950902, -0.51974942,  0.98788256],
       [-0.00285286,  0.45026765,  1.7950933 ],
       [-0.21026694,  0.60826436,  1.07947693],
       [-1.31269416,  1.02261858,  1.21754931]])

In [33]:
large_arr = np.random.randn(150)

In [34]:
large_arr

array([-1.0132457 ,  1.09722644,  1.38144907, -0.80596779,  1.53858115,
       -1.11765328, -0.95204119, -0.7164978 ,  1.95594057, -0.33401248,
       -0.08656563, -1.07769608, -0.8079785 , -2.08846863, -1.32224732,
        1.88772281,  0.00756641,  1.8266835 , -1.08405696, -0.26294196,
        0.33307822,  1.82953826,  2.30737956,  0.78255287,  1.22162172,
       -0.69389724,  0.57007839, -0.51561396, -0.94123238,  1.1409234 ,
       -0.19584529,  1.65143297, -0.84581563, -0.36262692,  0.52447603,
       -0.03410915, -1.24942857,  1.54384011,  0.16070386,  0.35474212,
        0.82098169, -1.57291949, -0.61170085,  0.72029062, -0.59128765,
       -0.42690899,  0.5820739 , -0.95496166, -0.09642172,  0.42072059,
        0.16829213, -1.05754154,  0.48577886,  0.21143868,  0.49182125,
       -0.72637339,  1.7801858 , -1.05291509,  1.03849563, -0.94836642,
        0.24759319, -1.05159027, -0.1875073 ,  1.01250467,  1.08651365,
       -1.56852999, -0.90164781, -1.61654475,  0.53386811,  1.03

In [35]:
np.sort(large_arr)[::-1]

array([ 2.85577152,  2.30737956,  2.16276283,  1.95594057,  1.88772281,
        1.84292279,  1.82953826,  1.8266835 ,  1.79162311,  1.7801858 ,
        1.66839764,  1.65143297,  1.60583485,  1.54384011,  1.53858115,
        1.46358316,  1.46303126,  1.45359617,  1.44256622,  1.39910928,
        1.38144907,  1.22162172,  1.20515889,  1.20017374,  1.1409234 ,
        1.13351158,  1.09722644,  1.08651365,  1.03849563,  1.03198277,
        1.02315204,  1.01250467,  1.00380704,  1.00228036,  0.99890083,
        0.97534103,  0.87082818,  0.85198695,  0.82098169,  0.81669271,
        0.78255287,  0.75535989,  0.73778809,  0.72029062,  0.63733314,
        0.62998668,  0.62954568,  0.61411477,  0.59106731,  0.5820739 ,
        0.57007839,  0.54879388,  0.53396696,  0.53386811,  0.52447603,
        0.49182125,  0.48577886,  0.4772928 ,  0.46901168,  0.45319445,
        0.42072059,  0.40796854,  0.40630221,  0.36811635,  0.36397264,
        0.35474212,  0.33307822,  0.24759319,  0.21143868,  0.16

In [36]:
np.sort(large_arr)[::-1][int(0.05 * len(large_arr))]

1.8266835041111997

In [39]:
names = np.array(["A", "A", "B", "A", "C"])

In [40]:
np.unique(names)

array(['A', 'B', 'C'], dtype='<U1')

In [41]:
inta = np.array([1,1,1,2,3,1,1,2,3])

In [42]:
np.unique(inta)

array([1, 2, 3])