In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({'k1':['one', 'one', 'one', 'two', 'two', 'two', 'two'],
                                'k2': [1, 1, 2, 3, 3, 4, 4]})

In [4]:
df

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [5]:
df.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [6]:
df.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [7]:
df['v1'] = np.arange(7)

In [8]:
df

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [9]:
df.drop_duplicates(["k1"])

k1  k2  v1
0  one   1   0
3  two   3   3

In [10]:
# 중복되는 행이 있을 때 어느 행을 남길 것인가?
# 마지막 행을 남기려면 last!

df.drop_duplicates(["k1", "k2"], keep='last')

k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

In [11]:
df.drop_duplicates(["k1", "k2"], keep='first')

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [12]:
df.drop_duplicates(["k1", "k2"])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [13]:
df2 = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 
                             'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'],
                               'ounces': [4, 3, 12, 6, 7.5, 8 ,3, 5, 6]})

# bacon과 Bacon??

In [14]:
df2

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [15]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon',
    'corned beef': 'cow'
}

In [16]:
df2['animal'] = df2['food'].apply(lambda x: meat_to_animal[x.lower()])

In [17]:
df2

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [18]:
s =pd.Series([1., -999, 2., -999., -1000, 3.])

In [19]:
s

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [20]:
s2 = s.replace(-999, np.nan)

In [21]:
s2

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [22]:
s2.replace(np.nan, 0)

0       1.0
1       0.0
2       2.0
3       0.0
4   -1000.0
5       3.0
dtype: float64

In [23]:
s2.fillna(0)

0       1.0
1       0.0
2       2.0
3       0.0
4   -1000.0
5       3.0
dtype: float64

In [24]:
# 카테고리(category, 범주형)

In [25]:
df3 = pd.DataFrame({'id': [1,2,3,4,5,6], "raw_grade":['a','b','b','a','a','e']})

In [26]:
df3

id raw_grade
0   1         a
1   2         b
2   3         b
3   4         a
4   5         a
5   6         e

In [27]:
df3['grade'] = df3['raw_grade'].astype('category')

In [28]:
df3

id raw_grade grade
0   1         a     a
1   2         b     b
2   3         b     b
3   4         a     a
4   5         a     a
5   6         e     e

In [29]:
df3['grade']

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): [a, b, e]

In [30]:
 df3['grade'].cat.categories

Index(['a', 'b', 'e'], dtype='object')

In [31]:
df3['grade'].cat.categories = ['very good', 'good', 'very bad']

In [32]:
df3

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [33]:
df3['grade'] = df3['grade'].cat.set_categories(['very bad', 'bad', 'medium', 'good', 'very good'])

In [34]:
df3

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [35]:
df3['grade']

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (5, object): [very bad, bad, medium, good, very good]

In [36]:
df3.sort_values(by='grade')

id raw_grade      grade
5   6         e   very bad
1   2         b       good
2   3         b       good
0   1         a  very good
3   4         a  very good
4   5         a  very good

In [37]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [38]:
cats = pd.cut(ages, bins)

In [39]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [40]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [41]:
cats.codes
# 각 성분이 몇 번째 카테고리에 들어가 있는지 알려주는 코드

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [42]:
cats.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [43]:
df

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [47]:
group_names = ["Youth", 'YoungAdult', 'KiddeAged', 'Senior']

In [49]:
pd.cut(ages, bins, labels = group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, KiddeAged, KiddeAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < KiddeAged < Senior]

In [50]:
data = np.random.rand(20)
data

array([0.76753418, 0.02216463, 0.25344234, 0.15883969, 0.76465856,
       0.82473238, 0.84777698, 0.92686908, 0.36607324, 0.7242792 ,
       0.10723756, 0.53138638, 0.47093019, 0.63759261, 0.62401187,
       0.89484737, 0.87157378, 0.85995049, 0.72650467, 0.68215787])

In [52]:
pd.cut(data, 4, precision = 2)

# precision: 소수 몇째자리까지??

[(0.7, 0.93], (0.021, 0.25], (0.25, 0.47], (0.021, 0.25], (0.7, 0.93], ..., (0.7, 0.93], (0.7, 0.93], (0.7, 0.93], (0.7, 0.93], (0.47, 0.7]]
Length: 20
Categories (4, interval[float64]): [(0.021, 0.25] < (0.25, 0.47] < (0.47, 0.7] < (0.7, 0.93]]

In [53]:
data2 = np.random.randn(1000)
data2[:5]

array([ 1.25329538, -0.54994364, -0.02505783, -1.29402697, -1.11456448])

In [54]:
cats = pd.qcut(data2, 4,)

# 사분위수를 추출해서 구분하기

In [55]:
cats

[(0.693, 3.424], (-0.591, 0.0414], (-0.591, 0.0414], (-3.11, -0.591], (-3.11, -0.591], ..., (-0.591, 0.0414], (-0.591, 0.0414], (0.0414, 0.693], (0.693, 3.424], (0.0414, 0.693]]
Length: 1000
Categories (4, interval[float64]): [(-3.11, -0.591] < (-0.591, 0.0414] < (0.0414, 0.693] < (0.693, 3.424]]